# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- master
pool:
  Default
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'npm install'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'npm run build.azure'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Test'
    organization: 'sahanaumesh'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Test17'
    cliProjectName: 'sahanasu93'
    cliSources: '.'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'